name: virtualmouse
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.9
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - mouseinfo==0.1.3
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pymsgbox==1.0.9
      - pyperclip==1.8.2
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - pytweening==1.2.0
